export { default as Movies } from './Movies'
export { default as Details } from './Movies/Details'
export { default as Discover } from './Movies/Discover'
export { default as Trending } from './Movies/Trending'
export { default as Genres } from './Movies/Genres'
